# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitPrompt < Formula
  desc ""
  homepage ""
  version "1.1.0"

  on_macos do
    on_intel do
      url "https://github.com/Ladicle/git-prompt/releases/download/v1.1.0/git-prompt_Darwin_x86_64.tar.gz"
      sha256 "24fb54ee1f3c93c692b746d74711bd13817f01ea155b22caebd38a792611c793"

      def install
        bin.install "git-prompt"
      end
    end
    on_arm do
      url "https://github.com/Ladicle/git-prompt/releases/download/v1.1.0/git-prompt_Darwin_arm64.tar.gz"
      sha256 "25e0b3702e831bc9c716862ae1c7c2a907e5aed7ea013a5b289541277777453f"

      def install
        bin.install "git-prompt"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Ladicle/git-prompt/releases/download/v1.1.0/git-prompt_Linux_x86_64.tar.gz"
        sha256 "6e0cab697d79e7a360bff1d07d794ff0c3551b837166f014fed65f693980db6e"

        def install
          bin.install "git-prompt"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Ladicle/git-prompt/releases/download/v1.1.0/git-prompt_Linux_arm64.tar.gz"
        sha256 "63c97abbf4fd85f8cd406becb9580e99b41d1b1a35292fbcd6c88fc5bb62feab"

        def install
          bin.install "git-prompt"
        end
      end
    end
  end
end
