# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ho < Formula
  desc ""
  homepage ""
  version "2.0.4"

  on_macos do
    on_intel do
      url "https://github.com/Ladicle/gha-playground/releases/download/v2.0.4/gha-playground_Darwin_x86_64.tar.gz"
      sha256 "dbc469a1181d7545f689493a6a1394e56c88835ce1d39c0ca664241e0f0681a3"

      def install
        bin.install "hello"
      end
    end
    on_arm do
      url "https://github.com/Ladicle/gha-playground/releases/download/v2.0.4/gha-playground_Darwin_arm64.tar.gz"
      sha256 "fd874c750eab0bdecb55699892f38e3efbd0693af76943bd753bfdadcbbe372b"

      def install
        bin.install "hello"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Ladicle/gha-playground/releases/download/v2.0.4/gha-playground_Linux_x86_64.tar.gz"
        sha256 "a22db18cd45d72df702664609b6d4d791b6b5b75e6aa13f8847ed1f3e25b254b"

        def install
          bin.install "hello"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Ladicle/gha-playground/releases/download/v2.0.4/gha-playground_Linux_arm64.tar.gz"
        sha256 "73bcc705f11cfd3a9d8d66c3c3c9170710254b97b777ba683b0a333bef451b33"

        def install
          bin.install "hello"
        end
      end
    end
  end
end
