# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KubectlCheck < Formula
  desc ""
  homepage ""
  version "1.2.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Ladicle/kubectl-check/releases/download/v1.2.1/kubectl-check_1.2.1_darwin_amd64.tar.gz"
      sha256 "a2ead7ace85940c43627220245aa1e56f85d1b78a4c2176e75db6c4c6536aa5a"

      def install
        bin.install "kubectl-check"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Ladicle/kubectl-check/releases/download/v1.2.1/kubectl-check_1.2.1_darwin_arm64.tar.gz"
      sha256 "821d1c85ecf2e71fda2d9874c1e73916e5b2af8d2b2195ecf19b62ab7c8102ae"

      def install
        bin.install "kubectl-check"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Ladicle/kubectl-check/releases/download/v1.2.1/kubectl-check_1.2.1_linux_amd64.tar.gz"
      sha256 "10e4427c9f3eedd71488d9cfe2fd77795d408411d24188ca9a820bb2c175b760"
      def install
        bin.install "kubectl-check"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Ladicle/kubectl-check/releases/download/v1.2.1/kubectl-check_1.2.1_linux_arm64.tar.gz"
      sha256 "f121f46a44361aec24015dd1e00158184fd3a4fa4f0c1e02afb4e6fc651ccf70"
      def install
        bin.install "kubectl-check"
      end
    end
  end
end
