# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KubectlEvict < Formula
  desc ""
  homepage ""
  version "0.4.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Ladicle/kubectl-evict/releases/download/v0.4.0/kubectl-evict_0.4.0_darwin_amd64.tar.gz"
      sha256 "d88de373b3db1851f3a64921f2cf314877b26416d04566164ed3f9ae9ffa3157"

      def install
        bin.install "kubectl-evict"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Ladicle/kubectl-evict/releases/download/v0.4.0/kubectl-evict_0.4.0_darwin_arm64.tar.gz"
      sha256 "272523d3d4e8ce56111121cd5155edf3ad4f008796b26893eae8dd52046b0a0a"

      def install
        bin.install "kubectl-evict"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Ladicle/kubectl-evict/releases/download/v0.4.0/kubectl-evict_0.4.0_linux_amd64.tar.gz"
      sha256 "f49fa65db3a6ec4569cb4e8883a76d28b6acfaab2028514e43a940fb3b89791e"
      def install
        bin.install "kubectl-evict"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Ladicle/kubectl-evict/releases/download/v0.4.0/kubectl-evict_0.4.0_linux_arm64.tar.gz"
      sha256 "ef83271cf0bf3857af2686bfb1fc5909913c35956d44bd707ea772df71a0bfac"
      def install
        bin.install "kubectl-evict"
      end
    end
  end
end
