# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tcardgen < Formula
  desc ""
  homepage ""
  version "0.5.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Ladicle/tcardgen/releases/download/v0.5.0/tcardgen_Darwin_x86_64.tar.gz"
      sha256 "5ba01c2c3b804d43178728cdd650ca867ae2b2106d18987645ba6fa27b3f71c5"

      def install
        bin.install "tcardgen"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Ladicle/tcardgen/releases/download/v0.5.0/tcardgen_Darwin_arm64.tar.gz"
      sha256 "f631f39888cfc488c180177a691814eae6b2db91cd7171a14ac6c8b4ecd7d13c"

      def install
        bin.install "tcardgen"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Ladicle/tcardgen/releases/download/v0.5.0/tcardgen_Linux_x86_64.tar.gz"
        sha256 "52af5cabe7519e102d6968ef9fe01bdfd17a4812b4bb7bf7f8a1e6a66001ffe3"

        def install
          bin.install "tcardgen"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Ladicle/tcardgen/releases/download/v0.5.0/tcardgen_Linux_arm64.tar.gz"
        sha256 "317247fc5de103f6c23ae3183ef2f015e1cb82e4db7738bb7d3e64b01f9590f5"

        def install
          bin.install "tcardgen"
        end
      end
    end
  end
end
