# This file was generated by GoReleaser. DO NOT EDIT.
cask "kubectl-check" do
  name "kubectl-check"
  desc "A kubectl plugin to check the status of Kubernetes resources"
  homepage "https://github.com/Ladicle/kubectl-check"
  version "1.3.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kubectl-check"
  binary "kubectl_complete-check"
  bash_completion "completions/kubectl-check.bash"
  zsh_completion "completions/kubectl-check.zsh"
  fish_completion "completions/kubectl-check.fish"

  on_macos do
    on_intel do
      url "https://github.com/Ladicle/kubectl-check/releases/download/v#{version}/kubectl-check_#{version}_darwin_amd64.tar.gz"
      sha256 "dbc422291b3ef0a7d2b2c4fba51a7bcea5c240e761f5c05dcb0faeca1e323243"
    end
    on_arm do
      url "https://github.com/Ladicle/kubectl-check/releases/download/v#{version}/kubectl-check_#{version}_darwin_arm64.tar.gz"
      sha256 "306e7723b9b2142c5f9f417d5b239be0654294726f155264fb5030dff92db904"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/Ladicle/kubectl-check/releases/download/v#{version}/kubectl-check_#{version}_linux_amd64.tar.gz"
      sha256 "fb38a595abf02b756a1471541824248729ecd615d2453bab27eeb6347e9bde29"
    end
    on_arm do
      url "https://github.com/Ladicle/kubectl-check/releases/download/v#{version}/kubectl-check_#{version}_linux_arm64.tar.gz"
      sha256 "53b46d45546b04ae38d293f56592eb08587cacd773d61b78fdd1926a54c20ba3"
    end
  end

  # No zap stanza required
end
