# This file was generated by GoReleaser. DO NOT EDIT.
cask "kubectl-check" do
  name "kubectl-check"
  desc "A kubectl plugin to check the status of Kubernetes resources"
  homepage "https://github.com/Ladicle/kubectl-check"
  version "1.5.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kubectl-check"
  binary "kubectl_complete-check"
  bash_completion "completions/kubectl-check.bash"
  zsh_completion "completions/kubectl-check.zsh"
  fish_completion "completions/kubectl-check.fish"

  on_macos do
    on_intel do
      url "https://github.com/Ladicle/kubectl-check/releases/download/v#{version}/kubectl-check_#{version}_darwin_amd64.tar.gz"
      sha256 "30999a1e9f5fa116dac11579f9b85ab59e3335b730526ac9564e9156c6af8d66"
    end
    on_arm do
      url "https://github.com/Ladicle/kubectl-check/releases/download/v#{version}/kubectl-check_#{version}_darwin_arm64.tar.gz"
      sha256 "a8f9dfd2e416733cfb31194914a92b8ef18aee6e616e02c11dba14bdf662c18b"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/Ladicle/kubectl-check/releases/download/v#{version}/kubectl-check_#{version}_linux_amd64.tar.gz"
      sha256 "fb041436a9e710b013d074b930eeb759bb21fbedd9139e885733c16b8cc1db84"
    end
    on_arm do
      url "https://github.com/Ladicle/kubectl-check/releases/download/v#{version}/kubectl-check_#{version}_linux_arm64.tar.gz"
      sha256 "fab0ef2e6af22112b2acb680bce052ddec2c7d551a2c7bcad2e50eba6c1ddeb7"
    end
  end

  # No zap stanza required
end
