# This file was generated by GoReleaser. DO NOT EDIT.
cask "kubectl-check" do
  name "kubectl-check"
  desc "A kubectl plugin to check the status of Kubernetes resources"
  homepage "https://github.com/Ladicle/kubectl-check"
  version "1.4.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kubectl-check"
  binary "kubectl_complete-check"
  bash_completion "completions/kubectl-check.bash"
  zsh_completion "completions/kubectl-check.zsh"
  fish_completion "completions/kubectl-check.fish"

  on_macos do
    on_intel do
      url "https://github.com/Ladicle/kubectl-check/releases/download/v#{version}/kubectl-check_#{version}_darwin_amd64.tar.gz"
      sha256 "c5fe310b89e499c4e8181a8993d3fed3e138b55f5e6146be370c3fe1c09b44f0"
    end
    on_arm do
      url "https://github.com/Ladicle/kubectl-check/releases/download/v#{version}/kubectl-check_#{version}_darwin_arm64.tar.gz"
      sha256 "4361b53544b64b89149221481d4aaa172dd80542e54a41277e191e370a35752b"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/Ladicle/kubectl-check/releases/download/v#{version}/kubectl-check_#{version}_linux_amd64.tar.gz"
      sha256 "9aeb0b8bdbabfa05afd2c13a69513ca39e78833346ae8a837e62832cfd262a86"
    end
    on_arm do
      url "https://github.com/Ladicle/kubectl-check/releases/download/v#{version}/kubectl-check_#{version}_linux_arm64.tar.gz"
      sha256 "b3169d99e64520a513c622583a047368d36debb09f59e11c78a43e607d7cb9fd"
    end
  end

  # No zap stanza required
end
