# This file was generated by GoReleaser. DO NOT EDIT.
cask "kubectl-evict" do
  name "kubectl-evict"
  desc "A kubectl plugin to evict Pods."
  homepage "https://github.com/Ladicle/kubectl-evict"
  version "0.6.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kubectl-evict"
  binary "kubectl_complete-evict"
  bash_completion "completions/kubectl-evict.bash"
  zsh_completion "completions/kubectl-evict.zsh"
  fish_completion "completions/kubectl-evict.fish"

  on_macos do
    on_intel do
      url "https://github.com/Ladicle/kubectl-evict/releases/download/v#{version}/kubectl-evict_#{version}_darwin_amd64.tar.gz"
      sha256 "20879583d297d1b5054989fa40c340fe6d848c2a9f71bfbea96c7c17337986fa"
    end
    on_arm do
      url "https://github.com/Ladicle/kubectl-evict/releases/download/v#{version}/kubectl-evict_#{version}_darwin_arm64.tar.gz"
      sha256 "eaab3a24f528df7cb159a09cb9ee2c88b3dd71e4f7ec1d69867a474b9e91b4e2"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/Ladicle/kubectl-evict/releases/download/v#{version}/kubectl-evict_#{version}_linux_amd64.tar.gz"
      sha256 "bea3a2f43debd0b13bc04d6a84d95c9730fdf6de8c84703ed5ff8031948489e8"
    end
    on_arm do
      url "https://github.com/Ladicle/kubectl-evict/releases/download/v#{version}/kubectl-evict_#{version}_linux_arm64.tar.gz"
      sha256 "3f2f6d13e05d3bd4034b2490912e3c3dadb7965f94250e67d9222a9d3ed0c859"
    end
  end

  # No zap stanza required
end
